### ISSUE TITLE
module load error, undefined symbol `fz_identity`

### ISSUE THREAD

**Issue by Hugo-Heagren** [ymarco/paper-mode#3]
I know this project is archived, but it looks really cool (and you've put in a lot of work!) and I've got all the modules to compile properly. I'm pretty happy to hack about on it, especially the elisp, but I don't know enough C to get over this one problem. I feel like it's probably pretty minor, so I'm posting an issue just to see if I can get it to work.

The modules compile with the following warnings:
```
make
cc -Wall -Wextra -Wno-unused-parameter -Wshadow -std=c99 -fpic `pkg-config --cflags gtk+-3.0 cairo` -lm -lmupdf   -c -o paper-module.o paper-module.c
paper-module.c: In function ‘Fpaper_new’:
paper-module.c:35:15: warning: unused variable ‘channel’ [-Wunused-variable]
   emacs_value channel = args[0];
               ^~~~~~~
At top level:
paper-module.c:25:17: warning: ‘paper_view_close’ defined but not used [-Wunused-function]
 static gboolean paper_view_close(Client *c) {
                 ^~~~~~~~~~~~~~~~
cc -Wall -Wextra -Wno-unused-parameter -Wshadow -std=c99 -fpic `pkg-config --cflags gtk+-3.0 cairo` -lm -lmupdf   -c -o PaperView.o PaperView.c
cc -Wall -Wextra -Wno-unused-parameter -Wshadow -std=c99 -fpic `pkg-config --cflags gtk+-3.0 cairo` -lm -lmupdf -fvisibility=hidden   -c -o symbols.o symbols.c
cc -Wall -Wextra -Wno-unused-parameter -Wshadow -std=c99 -fpic `pkg-config --cflags gtk+-3.0 cairo` -lm -lmupdf -shared `pkg-config --libs gtk+-3.0 cairo` -o paper-module.so paper-module.o PaperView.o symbols.o

Compilation finished at Sat Feb 11 12:12:55
```

And then when trying to load the module (e.g. `(require 'paper-module)`, or `(module-load (concat default-directory "paper-module.so"))` , I get the following error: `(module-open-failed "/home/hugo/.config/emacs/straight/build/paper/paper-module.so" "/home/hugo/.config/emacs/straight/build/paper/paper-module.so: undefined symbol: fz_identity")`.

What am I doing wrong?

**Comment by ymarco** [comment]
Yeah, linking errors like this are why I stopped development. See #1

**Comment by ymarco** [comment]
Hugo-Heagren ***@***.***> writes:

> I know this project is archived, but it looks really cool (and you've put in a lot of work!) and I've got all the modules to compile properly.

No, the problem from the beginning was the fz_identity symbol thing. I don't know how to solve it without introducing some other error that prevents from running the module.
Getting it to compile is easy.
